package de.osca.fama.smarthomeadapter.homeassistant

enum class HomeAssistantComponent {
    ALARM_CONTROL_PANEL,
    BINARY_SENSOR,
    BUTTON,
    CAMERA,
    COVER,
    DEVICE_TRACKER,
    DEVICE_TRIGGER,
    EVENT,
    FAN,
    HUMIDIFIER,
    IMAGE,
    CLIMATE_HVAC,
    LAWN_MOWER,
    LIGHT,
    LOCK,
    NOTIFY,
    NUMBER,
    SCENE,
    SELECT,
    SENSOR,
    SIREN,
    SWITCH,
    UPDATE,
    TAG_SCANNER,
    TEXT,
    VACUUM,
    VALVE,
    WATER_HEATER,
}
